eval:
  benchmark: unified_bench
inference:
  backbone: omnigen2
  backbone_cfg:
    model_path: /post_train_model_cache/post_train/omnigen2/
    omnigen2_root: /workspace/model/OmniGen2
    device: cuda:0
    torch_dtype: bfloat16
    generation_cfg:
      num_inference_steps: 50
      text_guidance_scale: 4.0
    understanding_cfg:
      max_new_tokens: 512
      repetition_penalty: 1.2
      do_sample: true
      temperature: 0.7
      top_p: 0.9
unified_bench:
  mode: generate
  ref_dir: /datasets/unified_bench/Image
  out_dir: /output-apr4/unified_bench/omnigen2_sft
  resume: true
  max_samples: 0
  score_output_path: /output-apr4/unified_bench/omnigen2_sft/summary.json
  captioning_instruction: 'You are an expert vision-language model.

    Your task is: Given an input image, generate a **textual description** of the
    image. If there is text in the image, transcribe it inside double quotes "".

    Now, carefully analyze the input image and output the full description.

    '
  scoring:
    models:
    - clip
    - dinov2
    - dinov3
    - longclip
    model_paths:
      clip: /model_cache/unified_bench/clip-vit-large-patch14
      dinov2: /model_cache/unified_bench/dinov2-large
      dinov3: /model_cache/unified_bench/dinov3-vitl16
      longclip: /model_cache/unified_bench/longclip-L.pt
    device: cuda
  score_model: unified_bench
  score_gpu: A100-40GB:1
