eval:
  benchmark: mmbench

inference:
  backbone: show-o2
  backbone_cfg:
    version: 2
    model_path: /post_train_model_cache/post_train/show_o2/unwrapped_model
    show_o_root: /workspace/model/Show-o
    vae_path: /model_cache/show_o2/Wan2.1_VAE.pth
    seed: 42
    torch_dtype: bfloat16
    understanding_cfg:
      max_new_tokens: 10
      do_sample: false
      use_clip_vit: true

mmbench:
  datasets: [MMBench_TEST_EN_V11, MMBench_TEST_CN_V11]
  out_dir: /output-apr4/mmbench/show_o2_sft-underN10
  score_output_path: /output-apr4/mmbench/show_o2_sft-underN10/summary.json
  mode: full
  resume: true
  score_model: wise
  score_gpu: "A100-80GB"
  llm_extract:
    model_path: /model_cache/evaluator/Qwen3-32B-AWQ
    max_new_tokens: 64
