eval:
  benchmark: mmbench

inference:
  backbone: bagel
  backbone_cfg:
    model_path: /post_train_model_cache/post_train/recA/
    checkpoint_file: model.safetensors
    bagel_root: /workspace/model/Bagel
    max_mem_per_gpu: 80GiB
    offload_folder: ./tmp/offload
    seed: 42

    understanding_cfg:
      max_think_token_n: 1000
      do_sample: false

mmbench:
  datasets: [MMBench_TEST_EN_V11, MMBench_TEST_CN_V11]
  out_dir: /outputs/mmbench/bagel_recA
  score_output_path: /outputs/mmbench/bagel_recA/summary.json
  mode: score
  resume: true
  score_model: wise
  score_gpu: "A100-80GB"
  llm_extract:
    model_path: /model_cache/evaluator/Qwen3-32B-AWQ
    max_new_tokens: 64
