eval:
  benchmark: mmbench

inference:
  backbone: ovis_u1
  backbone_cfg:
    model_path: /model_cache/ovis_u1/Ovis-U1-3B
    understanding_cfg:
      max_new_tokens: 5120
      do_sample: false

mmbench:
  datasets: [MMBench_TEST_EN_V11, MMBench_TEST_CN_V11]
  out_dir: /output-apr4/mmbench/ovis_u1-underN5120
  score_output_path: /output-apr4/mmbench/ovis_u1-underN5120/summary.json
  mode: score
  resume: true
  score_model: wise
  score_gpu: "A100-80GB"
  llm_extract:
    model_path: /model_cache/evaluator/Qwen3-32B-AWQ
    max_new_tokens: 64
