_wandb:
    value:
        cli_version: 0.25.1
        e:
            qkcmyynl74atzoks99e5vjesg0sknn5y:
                args:
                    - --model_path
                    - /sciclone/data10/yluo13/project/codebase/model_cache/janus/models/Janus_pro_7B
                    - --data_json
                    - /sciclone/data10/yluo13/project/umm_reasoning/dataset/t2i/prompts.json
                    - --image_root
                    - /sciclone/data10/yluo13/project/umm_reasoning/dataset/t2i
                    - --image_size
                    - "384"
                    - --vq_downsample
                    - "16"
                    - --batch_size
                    - "1"
                    - --gradient_accumulation_steps
                    - "1"
                    - --total_steps
                    - "5000"
                    - --lr
                    - "1e-5"
                    - --warmup_steps
                    - "100"
                    - --log_every
                    - "1"
                    - --save_every
                    - "1000"
                    - --checkpoint_dir
                    - results/checkpoints
                    - --wandb_project
                    - janus-posttrain
                    - --wandb_name
                    - t2i
                    - --wandb_offline
                    - "false"
                codePath: train/post_train.py
                codePathLocal: train/post_train.py
                cpu_count: 48
                cpu_count_logical: 48
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "1876484784128"
                        used: "213916569600"
                email: yinyil@andrew.cmu.edu
                executable: /sciclone/data10/yluo13/.conda/envs/janus/bin/python3.11
                gpu: NVIDIA H100 NVL
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "100485038080"
                      name: NVIDIA H100 NVL
                      uuid: GPU-bc470d98-0d49-8419-f8b1-8c82713a9181
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "100485038080"
                      name: NVIDIA H100 NVL
                      uuid: GPU-c65fa365-3b68-65d0-a679-c3a0278d20c7
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "100485038080"
                      name: NVIDIA H100 NVL
                      uuid: GPU-ab68e001-e4e3-46cc-7c36-a143e0e51030
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "100485038080"
                      name: NVIDIA H100 NVL
                      uuid: GPU-55e175de-b6e3-a346-72bc-9ad868bb9033
                host: test-h100
                memory:
                    total: "1081614585856"
                os: Linux-4.18.0-372.9.1.el8.x86_64-x86_64-with-glibc2.35
                program: /sciclone/data10/yluo13/project/umm_reasoning/Janus_pt/Janus/train/post_train.py
                python: CPython 3.11.14
                root: /sciclone/data10/yluo13/project/umm_reasoning/Janus_pt/Janus
                startedAt: "2026-04-20T15:53:56.117802Z"
                writerId: qkcmyynl74atzoks99e5vjesg0sknn5y
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 63
                - 71
            "2":
                - 1
                - 11
                - 41
                - 49
                - 63
                - 71
            "3":
                - 13
            "4": 3.11.14
            "5": 0.25.1
            "6": 4.37.2
            "12": 0.25.1
            "13": linux-x86_64
auto_resume:
    value: false
batch_size:
    value: 1
checkpoint_dir:
    value: results/checkpoints
data_json:
    value: /sciclone/data10/yluo13/project/umm_reasoning/dataset/t2i/prompts.json
epochs:
    value: 1
freeze_gen_vision:
    value: true
freeze_language:
    value: false
freeze_vision:
    value: true
global_seed:
    value: 4396
gradient_accumulation_steps:
    value: 1
image_root:
    value: /sciclone/data10/yluo13/project/umm_reasoning/dataset/t2i
image_size:
    value: 384
log_every:
    value: 1
lr:
    value: 1e-05
lr_scheduler:
    value: constant
max_samples:
    value: null
min_lr:
    value: 1e-07
model_path:
    value: /sciclone/data10/yluo13/project/codebase/model_cache/janus/models/Janus_pro_7B
num_workers:
    value: 4
output_dir:
    value: results
resume_from:
    value: null
resume_model_only:
    value: false
save_every:
    value: 1000
torch_dtype:
    value: bf16
total_steps:
    value: 5000
trust_remote_code:
    value: true
vq_downsample:
    value: 16
wandb_name:
    value: t2i
wandb_offline:
    value: false
wandb_project:
    value: janus-posttrain
warmup_steps:
    value: 100
